In [7]:
import pandas as pd
import numpy as numpy

In [8]:
data = pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
data

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [9]:
data.name="numbers"

In [10]:
data.size

5

In [11]:
len(data)

5

In [12]:
data.shape

(5,)

In [13]:
data.values

array([1, 2, 3, 4, 5])

In [14]:
data["a"],data["b"]

(1, 2)

In [15]:
data.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [16]:
data.loc["a"],data.iloc[3]

(1, 4)

In [17]:
data.loc[["a","b","c"]],data.iloc[3]

(a    1
 b    2
 c    3
 Name: numbers, dtype: int64,
 4)

In [18]:
#dataframes

In [19]:
dict={
    "usn":[2,3,4,1],
    "name":["san","ruthu","rithi","ruuu"],
    "age":[22,40,21,80],
    "branch":["cs","cs","ai","ds"]

}

In [20]:
df = pd.DataFrame(dict)
df

   usn   name  age branch
0    2    san   22     cs
1    3  ruthu   40     cs
2    4  rithi   21     ai
3    1   ruuu   80     ds

In [21]:
d=pd.read_csv(r"/Users/sanjananh/Downloads/sample.csv")
d

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
0,0,101,Ram,IT,25,50000,2,2021-01-15,Bangalore,4.5
1,1,102,Shyam,HR,30,45000,5,2019-03-10,Mumbai,3.8
2,2,103,Geeta,Finance,28,60000,4,2020-07-22,Delhi,4.2
3,3,104,Anita,IT,35,75000,10,2015-09-30,Bangalore,4.9
4,4,105,Kiran,HR,32,52000,7,2018-06-12,Mumbai,4.1
5,5,106,John,Finance,29,58000,3,2021-11-05,Delhi,3.9
6,6,107,Meena,IT,41,82000,15,2010-04-18,Bangalore,4.8
7,7,108,David,HR,26,48000,2,2022-02-14,Mumbai,3.7
8,8,109,Sara,Finance,38,61000,12,2013-12-01,Delhi,4.3
9,9,110,Arjun,IT,27,54000,4,2020-08-19,Bangalore,4.0
10,10,111,Ravi,HR,33,47000,6,2017-05-23,Mumbai,3.6
11,11,112,Priya,Finance,31,59000,5,2019-09-17,Delhi,4.4
12,12,113,Kunal,IT,45,90000,18,2008-03-11,Bangalore,4.9
13,13,114,Sneha,HR,29,51000,3,2021-07-29,Mumbai,3.5
14,14,115,Vijay,Finance,36,62000,11,2014-01-10,Delhi,4.2
15,15,116,Neha,IT,40,88000,14,2011-10-21,Bangalore,4.7
16,16,117,Amit,HR,34,53000,8,2016-04-05,Mumbai,4.0
17,17,118,Pooja,Finance,30,57000,6,2018-12-12,Delhi,4.1
18,18,119,Rahul,IT,28,56000,4,2020-02-28,Bangalore,3.9
19,19,120,Divya,HR,37,49500,9,2015-06-30,Mumbai,4.3

In [22]:
d.head(3)

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
0,0,101,Ram,IT,25,50000,2,2021-01-15,Bangalore,4.5
1,1,102,Shyam,HR,30,45000,5,2019-03-10,Mumbai,3.8
2,2,103,Geeta,Finance,28,60000,4,2020-07-22,Delhi,4.2

In [23]:
d.tail()

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
15,15,116,Neha,IT,40,88000,14,2011-10-21,Bangalore,4.7
16,16,117,Amit,HR,34,53000,8,2016-04-05,Mumbai,4.0
17,17,118,Pooja,Finance,30,57000,6,2018-12-12,Delhi,4.1
18,18,119,Rahul,IT,28,56000,4,2020-02-28,Bangalore,3.9
19,19,120,Divya,HR,37,49500,9,2015-06-30,Mumbai,4.3

In [24]:
d.describe()

,Unnamed: 0,EmpID,Age,Salary,Experience,PerformanceScore
count,20.00000,20.00000,20.000000,20.000000,20.000000,20.000000
mean,9.50000,110.50000,32.700000,59875.000000,7.400000,4.190000
std,5.91608,5.91608,5.449288,13388.796377,4.615762,0.415363
min,0.00000,101.00000,25.000000,45000.000000,2.000000,3.500000
25%,4.75000,105.75000,28.750000,50750.000000,4.000000,3.900000
50%,9.50000,110.50000,31.500000,56500.000000,6.000000,4.150000
75%,14.25000,115.25000,36.250000,61250.000000,10.250000,4.425000
max,19.00000,120.00000,45.000000,90000.000000,18.000000,4.900000

In [25]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        20 non-null     int64
 1   EmpID             20 non-null     int64
 2   Name              20 non-null     object
 3   Department        20 non-null     object
 4   Age               20 non-null     int64
 5   Salary            20 non-null     int64
 6   Experience        20 non-null     int64
 7   JoiningDate       20 non-null     object
 8   City              20 non-null     object
 9   PerformanceScore  20 non-null     float64
dtypes: float64(1), int64(5), object(4)
memory usage: 1.7+ KB

In [26]:
d.shape

(20, 10)

In [27]:
#hypothisis testing explain

In [28]:
d[["Name","Department","Salary"]].head(2)

    Name Department  Salary
0    Ram         IT   50000
1  Shyam         HR   45000

In [29]:
type(d.Name)

pandas.core.series.Series

In [30]:
t=pd.read_csv(r"/Users/sanjananh/Downloads/test2.csv")
t

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [31]:
t.isnull().sum()

Unnamed: 0    0
Name          0
Age           1
Department    0
Salary        1
dtype: int64

In [32]:
t.isnull()

   Unnamed: 0   Name    Age  Department  Salary
0       False  False  False       False   False
1       False  False  False       False   False
2       False  False  False       False   False
3       False  False   True       False   False
4       False  False  False       False    True
5       False  False  False       False   False

In [33]:
t.loc[1:3,"Name":"Department"]

      Name   Age Department
1      Bob  30.0         IT
2  Charlie  35.0    Finance
3    David   NaN         IT

In [34]:
t.iloc[1:4,1:4]

      Name   Age Department
1      Bob  30.0         IT
2  Charlie  35.0    Finance
3    David   NaN         IT

In [35]:
t.rename(columns={"Name":"N","Age":"A","Department":"D","Salary":"S"},inplace=True)
t

   Unnamed: 0        N     A        D        S
0           0    Alice  25.0       HR  50000.0
1           1      Bob  30.0       IT  60000.0
2           2  Charlie  35.0  Finance  70000.0
3           3    David   NaN       IT  62000.0
4           4      Eve  29.0       HR      NaN
5           5    Alice  25.0       HR  50000.0

In [36]:
t.drop('Unnamed: 0',axis=1,inplace=True)

In [37]:
t

         N     A        D        S
0    Alice  25.0       HR  50000.0
1      Bob  30.0       IT  60000.0
2  Charlie  35.0  Finance  70000.0
3    David   NaN       IT  62000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  50000.0

In [38]:
#axis1 is for rows 0 for coloums in numpy its different

In [39]:
t["updated_salary"]=t["S"]+5000
t

         N     A        D        S  updated_salary
0    Alice  25.0       HR  50000.0         55000.0
1      Bob  30.0       IT  60000.0         65000.0
2  Charlie  35.0  Finance  70000.0         75000.0
3    David   NaN       IT  62000.0         67000.0
4      Eve  29.0       HR      NaN             NaN
5    Alice  25.0       HR  50000.0         55000.0

In [40]:
t["updated_salary_2"]=t["S"].map(lambda X:X+10000)
t

         N     A        D        S  updated_salary  updated_salary_2
0    Alice  25.0       HR  50000.0         55000.0           60000.0
1      Bob  30.0       IT  60000.0         65000.0           70000.0
2  Charlie  35.0  Finance  70000.0         75000.0           80000.0
3    David   NaN       IT  62000.0         67000.0           72000.0
4      Eve  29.0       HR      NaN             NaN               NaN
5    Alice  25.0       HR  50000.0         55000.0           60000.0

In [41]:
t.head()

         N     A        D        S  updated_salary  updated_salary_2
0    Alice  25.0       HR  50000.0         55000.0           60000.0
1      Bob  30.0       IT  60000.0         65000.0           70000.0
2  Charlie  35.0  Finance  70000.0         75000.0           80000.0
3    David   NaN       IT  62000.0         67000.0           72000.0
4      Eve  29.0       HR      NaN             NaN               NaN

In [42]:
t=pd.read_csv(r"/Users/sanjananh/Downloads/test2.csv")
t

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [43]:
t["updated_salary"]=t["Salary"]+5000
t

   Unnamed: 0     Name   Age Department   Salary  updated_salary
0           0    Alice  25.0         HR  50000.0         55000.0
1           1      Bob  30.0         IT  60000.0         65000.0
2           2  Charlie  35.0    Finance  70000.0         75000.0
3           3    David   NaN         IT  62000.0         67000.0
4           4      Eve  29.0         HR      NaN             NaN
5           5    Alice  25.0         HR  50000.0         55000.0

In [44]:
t["updated_salary_2"]=t["Salary"].map(lambda X:X+10000)
t

,Unnamed: 0,Name,Age,Department,Salary,updated_salary,updated_salary_2
0,0,Alice,25.0,HR,50000.0,55000.0,60000.0
1,1,Bob,30.0,IT,60000.0,65000.0,70000.0
2,2,Charlie,35.0,Finance,70000.0,75000.0,80000.0
3,3,David,NaN,IT,62000.0,67000.0,72000.0
4,4,Eve,29.0,HR,NaN,NaN,NaN
5,5,Alice,25.0,HR,50000.0,55000.0,60000.0

In [45]:
t.dropna(inplace=True)

In [46]:
t.isnull().sum()

Unnamed: 0          0
Name                0
Age                 0
Department          0
Salary              0
updated_salary      0
updated_salary_2    0
dtype: int64

In [47]:
t["Age"]=t.Age.astype("int")
t

,Unnamed: 0,Name,Age,Department,Salary,updated_salary,updated_salary_2
0,0,Alice,25,HR,50000.0,55000.0,60000.0
1,1,Bob,30,IT,60000.0,65000.0,70000.0
2,2,Charlie,35,Finance,70000.0,75000.0,80000.0
5,5,Alice,25,HR,50000.0,55000.0,60000.0

In [48]:
t[t["Age"]>25]

,Unnamed: 0,Name,Age,Department,Salary,updated_salary,updated_salary_2
1,1,Bob,30,IT,60000.0,65000.0,70000.0
2,2,Charlie,35,Finance,70000.0,75000.0,80000.0

In [49]:
t=pd.read_csv(r"/Users/sanjananh/Downloads/test2.csv")

In [50]:
t

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [51]:
t.isnull().sum()

Unnamed: 0    0
Name          0
Age           1
Department    0
Salary        1
dtype: int64

In [52]:
t["Age"].mean

<bound method Series.mean of 0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64>

In [55]:
t["Age"]=t["Age"].fillna(value=t["Age"].mean())
t

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David  28.8         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [56]:
t["Salary"].mean

<bound method Series.mean of 0    50000.0
1    60000.0
2    70000.0
3    62000.0
4        NaN
5    50000.0
Name: Salary, dtype: float64>

In [57]:
t["Salary"]=t["Salary"].fillna(value=t["Salary"].mean())
t

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David  28.8         IT  62000.0
4           4      Eve  29.0         HR  58400.0
5           5    Alice  25.0         HR  50000.0

In [58]:
t["Department"].value_counts()

Department
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [59]:
t["Age"].fillna(method="ffill")
t["Salary"].fillna(method="bfill")

/var/folders/h1/qrjgcyx14ws2h902ypwsx16w0000gn/T/ipykernel_1813/482109868.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  t["Age"].fillna(method="ffill")
/var/folders/h1/qrjgcyx14ws2h902ypwsx16w0000gn/T/ipykernel_1813/482109868.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  t["Salary"].fillna(method="bfill")

0    50000.0
1    60000.0
2    70000.0
3    62000.0
4    58400.0
5    50000.0
Name: Salary, dtype: float64

In [60]:
t

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David  28.8         IT  62000.0
4           4      Eve  29.0         HR  58400.0
5           5    Alice  25.0         HR  50000.0

In [61]:
t=pd.read_csv(r"/Users/sanjananh/Downloads/test2.csv")
t

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [62]:
t["Age"]=t["Age"].fillna(method="ffill")
t["Salary"]=t["Salary"].fillna(method="bfill")
t

/var/folders/h1/qrjgcyx14ws2h902ypwsx16w0000gn/T/ipykernel_1813/788801895.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  t["Age"]=t["Age"].fillna(method="ffill")
/var/folders/h1/qrjgcyx14ws2h902ypwsx16w0000gn/T/ipykernel_1813/788801895.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  t["Salary"]=t["Salary"].fillna(method="bfill")

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David  35.0         IT  62000.0
4           4      Eve  29.0         HR  50000.0
5           5    Alice  25.0         HR  50000.0

In [63]:
t.Age.ffill()

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [64]:
t["updated_salary"]=t["Salary"].apply(lambda x:x+10000)
t

   Unnamed: 0     Name   Age Department   Salary  updated_salary
0           0    Alice  25.0         HR  50000.0         60000.0
1           1      Bob  30.0         IT  60000.0         70000.0
2           2  Charlie  35.0    Finance  70000.0         80000.0
3           3    David  35.0         IT  62000.0         72000.0
4           4      Eve  29.0         HR  50000.0         60000.0
5           5    Alice  25.0         HR  50000.0         60000.0

In [65]:
t["level"]=t.apply(lambda s:"high" if s["Salary"]>60000 else "low",axis=1)

In [66]:
t

   Unnamed: 0     Name   Age Department   Salary  updated_salary level
0           0    Alice  25.0         HR  50000.0         60000.0   low
1           1      Bob  30.0         IT  60000.0         70000.0   low
2           2  Charlie  35.0    Finance  70000.0         80000.0  high
3           3    David  35.0         IT  62000.0         72000.0  high
4           4      Eve  29.0         HR  50000.0         60000.0   low
5           5    Alice  25.0         HR  50000.0         60000.0   low

In [68]:
t.groupby("Department")["Salary"].mean()

Department
Finance    70000.0
HR         50000.0
IT         61000.0
Name: Salary, dtype: float64